const data = {
    internships:[
        {
            _id:'1',
            name:'Support Engineer Intern',
            category: 'Part-time',
            image: '../images/micrologo1.jpg',
            company: 'Microsoft',
            location: 'Lisbon',
            candidates: '23',
            status: 'Open',
            type: 'Part-time',
            date:'3 days ago',
            description: 'Bla Bla Bla Bla',
        },
        {
            _id:'2',
            name:'Data Analyst Intern',
            category: 'Part-time',
            image: '../images/amazon.png',
            company: 'Amazon',
            location: 'Porto',
            candidates: '123',
            status: 'Open',
            type: 'Part-time',
            date:'9 days ago',
            description: 'Bla Bla Bla Bla',
        },
        {
            _id:'3',
            name:'Bussiness Analyst Intern',
            category: 'Part-time',
            image: '../images/cisco.jpeg',
            company: 'Cisco',
            location: 'Aveiro',
            candidates: '83',
            status: 'Open',
            type: 'Part-time',
            date:'2 weeks ago',
            description: 'Bla Bla Bla Bla Bla Bla Bla',
        },
        {
            _id:'4',
            name:'Strategic Sales Intern',
            category: 'Part-time',
            image: '../images/google.png',
            company: 'Google',
            location: 'Faro',
            candidates: '13',
            status: 'Closed',
            type: 'Part-time',
            date:'2 months ago',
            description: 'Bla Bla Bla Bla Bla',
        },
        {
            _id:'5',
            name:'Project Manager Intern',
            category: 'Part-time',
            image: '../images/sonae.png',
            company: 'Sonae',
            location: 'Lisbon',
            candidates: '43',
            status: 'Open',
            type: 'Part-time',
            date:'1 week ago',
            description: 'Bla Bla Bla Bla Bla',
        },
        {
            _id:'6',
            name:'RH Intern',
            category: 'Part-time',
            image: '../images/NOS.png',
            company: 'NOS',
            location: 'Lisboa',
            candidates: '27',
            status: 'Closed',
            type: 'Part-time',
            date:'2 weeks ago',
            description: 'Bla Bla Bla ',
        },
    ]
}

export default data;